{% set name = "unicodedata2" %}
{% set version = "15.0.0" %}
{% set sha256 = "ed6c683f7b0a58cd11824b440d8ad24b22904ab3f63fc851bbcd7e518fa68f2d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

test:
  imports:
    - unicodedata2
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mikekap/unicodedata2
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: unicodedata backport/updates to python 3 and python 2.
  description: unicodedata backport/updates to python 3 and python 2.
  dev_url: https://github.com/mikekap/unicodedata2
  doc_url: https://docs.python.org/3/library/unicodedata.html

extra:
  recipe-maintainers:
    - CJ-Wright
    - dopplershift
