travis:
  secure:
    BINSTAR_TOKEN: M9YMqHbbkVIQ2QBevZqLi/cf9PUxgiK+Re1CEgTfMLv6R1APyjgeVsgFGHOIt9buAJMivYuIrlNOdMhCSu4MGWapfVz0FDlYbOZOeDM8/CUNgAtatGHCqHvLJhXWXkaSdRp/Sa0YlE9TAV2tiIirAgq3sxAdqcVA6aog5k6/DTygJhLv0WJeDNtWKWSoUH68mttPu2Vs1PY6hfMtF6zn3eHWONnD7JnrODY4pRrAOJXUjiQ33NvO7K6rVQKPexoIkwkLBigR7FTG72Q/KHmRCJjJtrFKXvsHadAurcYcqv6G7mL07wNe91f2yORcf/eNtFeyjMIC2fo550/cFFguAK0OcIgYu4/OgibGgXByeoHu+WlbKo+TR/aSPwk3xJlC9zv4ZnZUwSehkDYEWlUVCap8YLoaUm+WeBbwJXlOUk1dqgFvpxqY0/+ZG9683JXCy89XjCfSYk1hAS7PGXHCgxuzo/NK4V/uVx1njtAOV0AmS03DPMPOwxRNr9YG1GbcZaRwM70v80AmPjJ1TsW5UiHypuan9DqE6oF3+fDzgYb04rwXSf48HZLUhCKBDX5RHe15q9pd2jj4pTF5/ertkxI2MKKrc0iG3BltoEwZDl2hH+UTmdQEDMZ9lLmazbphzTPgH2NpxPYdh80u4GrmlOeqPLYeeQgcp21400aASfQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
